//constants
export const RESET_QUESTIONS="RESET_QUESTIONS"
export const RESET_USER="RESET_USER"
export const SET_IS_AUTHENTICATED="SET_IS_AUTHENTICATED"
export const SET_USERNAME="SET_USERNAME"
export const SET_ANSWER="SET_ANSWER"
export const SET_QUESTION_ANS_ARRAY="SET_QUESTION_ANS_ARRAY"